name: build

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # ...
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install
      - name: Build App
        run: bun run build
      - name: Update CHANGELOG
        id: changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: twitch-api-proxy
          body: |
            Download twitch-api-proxy Binary to run this version.

            # Changelog
            
            ${{ steps.changelog.outputs.changes }}
